# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0107852a2504d1031b6d21937f88cc08a5e532d42fd4fe0855c9c0f28dc8ff42603fd51a54452e3d13c28f937c485388fc79741bc281d046d0e819329581e0a7

test:
  secret_key_base: 8dae80e847e96f3a317306c007bea73e29c31cdbbac1954fdf0534ed8ec4991a0498cb0abd69f40d435cb7eec8e5feabcca1570ab3d06b2ed0921af9ee472fd5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
